query GetPins {
  pins {
    edges {
      node {
        ...Pins
        childPins {
          edges {
            node {
              ...Pins
            }
          }
        }
      }
    }
  }
}


fragment Pins on Pin {
  title
  slug
  link
  content
}